linux_x64_task:
  container:
    cpu: 2
    memory: 2G
    dockerfile: .ci/linux_x64/Dockerfile

  build_script:
    - cmake -B build
    - cmake --build build

  binaries_artifacts:
    path: build/AsmTool*.zip


windows_x86_task:
  windows_container:
    cpu: 2
    memory: 2G
    dockerfile: .ci/windows_x64/Dockerfile
    os_version: 2019

  build_script:
    - cmake -B build
    - cmake --build build

  binaries_artifacts:
    path: build/AsmTool*.zip
